### ISSUE TITLE
404 Page not found while adding note as non member

### ISSUE THREAD

**Issue by pkestefran** [AlphaNodes/redmine_tweaks#38] opened 2017-02-23 18:51 UTC
Hello, I have noticed that while I'm trying to post a note to issue as user who is not a member of a project I will receive error 404 Page not found. Can you please check? Thank you.

```
Started PATCH "/issues/11" for xx.xx.xx.xx at 2017-02-23 19:43:03 +0100
Processing by IssuesController#update as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"JwZT9e7XdAFPIiNXxxFZSa6axRmwfQoOemxgqAizg2H6QfmGQSSj+10kDVwjS5KTvsEECyoAfg/iC+eCqCK2Ag==", "issue"=>{"notes"=>"note added by project nonmember", "lock_version"=>"0"}, "last_journal_id"=>"", "commit"=>"Submit", "next_issue_id"=>"10", "issue_position"=>"1", "issue_count"=>"11", "id"=>"11"}
  Current user: testuser (id=6)
Completed 404 Not Found in 83ms (ActiveRecord: 35.0ms)

ActiveRecord::RecordNotFound (Couldn't find Role with 'id'=0 [WHERE ( builtin = 0)]):
  plugins/redmine_tweaks/lib/redmine_tweaks/patches/issue_patch.rb:33:in `auto_assign_user'
  plugins/redmine_tweaks/lib/redmine_tweaks/hooks.rb:31:in `issue_auto_assign'
  plugins/redmine_tweaks/lib/redmine_tweaks/hooks.rb:22:in `controller_issues_edit_before_save'
  lib/redmine/hook.rb:61:in `block (2 levels) in call_hook'
  lib/redmine/hook.rb:61:in `each'
  lib/redmine/hook.rb:61:in `block in call_hook'
  lib/redmine/hook.rb:58:in `tap'
  lib/redmine/hook.rb:58:in `call_hook'
  lib/redmine/hook.rb:91:in `call_hook'
  app/controllers/issues_controller.rb:514:in `block in save_issue_with_child_records'
  app/controllers/issues_controller.rb:503:in `save_issue_with_child_records'
  app/controllers/issues_controller.rb:179:in `update'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

```
Environment:
  Redmine version                3.3.1.stable
  Ruby version                   2.2.2-p95 (2015-04-13) [x86_64-linux-gnu]
  Rails version                  4.2.7.1
  Environment                    production
  Database adapter               Mysql2
SCM:
  Git                            1.7.1
  Filesystem                     
Redmine plugins:
  redmine_tweaks                 1.0.0
```

**Comment by alexandermeindl** [comment] 2017-02-24 14:23
Hi pkestefran, thanks for reporting this. I cannot reproduce your error. Can you check, if you autoassign setting on /settings/plugin/redmine_tweaks?tab=rules are assigned to an existing role. Try to resave this settings. If this solve the problem for you, maybe you deleted the role, which was selected in the tweaks settings?

If this does not solve the problem for you, can you provide me information about the user permission "non-member" role for issues?

**Comment by pkestefran** [comment] 2017-02-27 07:31
Hello Alexander, thanks for quick reply. I have recreated the prod db from scratch and loaded default data. Works as expected.

**Comment by alexandermeindl** [comment] 2017-02-27 07:50
Hi,
thanks for the feedback!

**Closed by alexandermeindl** 2017-02-27 07:50 UTC
